import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[url('/b.png')] bg-cover bg-center h-[50vh]">
        <Header />
        {children}
      </body>
    </html>
  );
}
